[gcp_service_account]
type = "service_account"
project_id = "stramlitdrive"
private_key_id = "7f8528734de027b47dd7cd9cf0a88badb63350fe"
private_key = "-----BEGIN PRIVATE KEY-----\n…\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-drive@stramlitdrive.iam.gserviceaccount.com"
client_id = "112859973208575937916"
token_uri = "https://oauth2.googleapis.com/token"

# ajoute l’ID du dossier Drive partagé au SA (2A)
drive_parent_folder_id = "1EYr1BvMAnjZbKF7WYDJs_66GVfe_qVfE"
